export { profile } from './profile.js'
export { socialLinks } from './social.js'
export type { SocialLink } from './social.js'
export { skills } from './skills.js'
export type { Skill } from './skills.js'
export { projects } from './projects.js'
export type { Project } from './projects.js'
