export { profile } from './profile'
export { socialLinks } from './social'
export type { SocialLink } from './social'
export { skills } from './skills'
export type { Skill } from './skills'
export { projects } from './projects'
export type { Project } from './projects'
